### ISSUE TITLE
No Map Recieved

### ISSUE THREAD

**Issue by jeychandar** [ros-perception/slam_gmapping#107]
@wjwwood Hi sir. I tried to create 2D Map for ouster os1-128 sensor and my launch file looks like this
![image](https://github.com/ros-perception/slam_gmapping/assets/48254471/11c7adff-8418-4e18-ad25-e2e7dd5f34a7)

Am unable to create 2d map. Could you please help me out with this issue. Thanks in advance

**Comment by q2421840278** [comment]
me too，do you solve it

**Comment by wjwwood** [comment]
This isn't a good question for this issue tracker, please consider asking on the robotics stack exchange, see: https://docs.ros.org/en/rolling/Contact.html#support

Also, when you ask questions there, consider including important context like what you're trying to do, what you've tried, and what version of ROS you're using.
