### ISSUE TITLE
Map mutexes do nothing

### ISSUE THREAD

**Issue by skohlbr** [ros-perception/slam_gmapping#11]
The mutexes used to lock the map structure do nothing, as only temporaries are created that go out of scope immediately after creation. Instead of

<pre>
boost::mutex::scoped_lock(map_mutex_);
</pre>

this should be used:

<pre>
boost::mutex::scoped_lock lock (map_mutex_);
</pre>

I only noticed this bug when carelessly copying some code from slam_gmapping and then getting crashes. Apparently, the mutexes aren´t that crucial in slam_gmapping though, as this bug has been there from the beginning years ago :)

**Comment by wjwwood** [comment]
:interrobang: Oh man, this is silly... I'll make a pull request...
