### ISSUE TITLE
gmapping needs re-release in Indigo

### ISSUE THREAD

**Issue by mikeferguson** [ros-perception/slam_gmapping#19]
It appears gmapping has not be re-released since https://github.com/ros-infrastructure/bloom/issues/277, needs to be debinc'd (its REALLY slow... hilariously slow in fact). This probably also applies to the underlying library.

**Comment by tfoote** [comment]
Ditto for hydro

**Comment by wjwwood** [comment]
Indigo: https://github.com/ros/rosdistro/pull/4713

**Comment by wjwwood** [comment]
Hydro: https://github.com/ros/rosdistro/pull/4715

**Comment by mikeferguson** [comment]
Thanks @wjwwood

**Comment by jonbinney** [comment]
Does re-releasing this fix the slowness? Isn't most of the code actually in https://github.com/ros-perception/openslam_gmapping ?

**Comment by mikeferguson** [comment]
Whoops, missed that the underlying library actually hadn't gotten debinc'd, I jumped the gun on closing this one.

**Comment by wjwwood** [comment]
Oops, yeah I should have know that too, I am blooming `openslam_gmapping` now.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/4762

**Comment by jonbinney** [comment]
Thanks @wjwwood!

**Comment by mikeferguson** [comment]
@wjwwood It looks like you debinc'd indigo twice, but didn't debinc hydro for openslam_gmapping?

**Comment by wjwwood** [comment]
Yeah, something weird happened to the hydro one, so it ended up inc'ing twice, I forgot to do the hydro one.

**Comment by wjwwood** [comment]
https://github.com/ros/rosdistro/pull/4764

**Comment by mikeferguson** [comment]
ah ok.. well I think that latest PR solves this ticket then. thanks @wjwwood!
