### ISSUE TITLE
There should be a way to set minimumScore (m_minimumscore) in openslam_gmapping through slam_gmapping

### ISSUE THREAD

**Issue by koenlek** [ros-perception/slam_gmapping#20]
In the original gmapping, there is an option to set 'minimumScore'. If the scan matcher scores lower than this, a scan match is regarded to be failed and the filter update will only be based on the odometry. By default, minimumScore is 0. To my knowledge, the scanmatcher will only score 0 if there is nothing at all (an open space). As soon as it sees something small, or only some straight wall that does not give much certainty, scores will become something like 0 to 150. The estimates based on these poor scan matches can make the pose estimate jump around quite a lot. I experienced this when driving a turtlebot (with e.g. kinect as laser, or the popular hokuyo urg 04lx ug01 which only has a range of 6m) in a simulated world in gazebo such as the willowgarage world. It will give serious performance issues in the large open area's. Gmapping will screw up badly.

I would suggest that slam_gmapping is adapted such that 'minimumScore' can be set such as all other parameters (e.g. xmin, lstep, kernelSize, etc). Now I just manually adapted the source of openslam_gmapping to use a custom minimumScore.

Kind regards,
Koen

**Comment by chadrockey** [comment]
@koenlek that sounds good.

Can you create a pull request with that change as a ros parameter?

**Comment by koenlek** [comment]
How should I do that when it involves two different repositories? And should I also update the doxygen and more of that kind of stuff to reflect the new possibility?

To summarize, for this repository:
- In https://github.com/ros-perception/slam_gmapping/blob/hydro-devel/gmapping/src/slam_gmapping.cpp add this instead of line 131:

```
ros::NodeHandle private_nh_("~");
  double minimum_score;
  if(!private_nh_.getParam("minimumScore", minimum_score))
    minimum_score = 0;
```

And remove line 144 (private nh needed to be moved up).

Then for the openslam_gmapping repository (https://github.com/ros-perception/openslam_gmapping):
- In https://github.com/ros-perception/openslam_gmapping/blob/master/include/gmapping/gridfastslam/gridslamprocessor.h add this behind line 129:

```
GridSlamProcessor(double minimumScore);
```
- In https://github.com/ros-perception/openslam_gmapping/blob/master/gridfastslam/gridslamprocessor.cpp add this block behind line 26:

```
GridSlamProcessor::GridSlamProcessor(double minimumScore): m_infoStream(cerr){
      period_ = 5.0;
      m_obsSigmaGain=1;
      m_resampleThreshold=0.5;
      m_minimumScore=minimumScore; //KL: was 0.
    }
```

**Comment by mikeferguson** [comment]
You shouldn't have to modify the GridSlamProcessor class, https://github.com/ros-perception/openslam_gmapping/blob/master/include/gmapping/gridfastslam/gridslamprocessor.h#L244 shows that you should be able to call "setminimumScore(double)" to set the score after the class instance is created. Thus, it should be possible to follow the same style as all the other parameters, and load the rosparam in the SlamGMapping constructor, and then set the GridSlamProcessor value in SlamGMapping::InitMapper.

**Comment by koenlek** [comment]
Done: see: https://github.com/ros-perception/slam_gmapping/pull/21

Just a question out of interest, as I am new to this kind of collaborative development: how is such an update incorporated in e.g. indigo-devel? And when could I expect these changes in the official Hydro/Indigo releases?

Best,
Koen

**Comment by chadrockey** [comment]
@koenlek 

Once your pull request is merged, then one of the maintainers will run the release process.  I think the maintainers are @vrabaud or @wjwwood 

Since this defaults to the old value, it should be backportable to hydro.

**Comment by wjwwood** [comment]
#21 was merged.
