### ISSUE TITLE
gmapping node assumes zero-centered scan range

### ISSUE THREAD

**Issue by windelbouwman** [ros-perception/slam_gmapping#25]
the gmapping node assumes a scan that is centered around 0 angle. As an example, a scan message from 0 to 2*pi yields distorted results. A scan from -pi to pi works correctly. I checked this with gazebo.

The node should at least exit with an assertion error when the scan data is not centered around 0 angle. Or, perhaps, convert the scan message to a format usable by the gmapping library.

**Comment by wjwwood** [comment]
@windelbouwman thanks for the report, unfortunately I don't have time to work on this. Maybe @vrabaud will have some time, but I know he is busy too.

If you find time to fix this for yourself please consider opening a pull request. Thanks!

**Comment by windelbouwman** [comment]
I added a check for this condition, and created a PR.

**Comment by wjwwood** [comment]
Addressed: https://github.com/ros-perception/slam_gmapping/pull/26
