### ISSUE TITLE
Does it have the branch of indigo? 

### ISSUE THREAD

**Issue by blueshark000** [ros-perception/slam_gmapping#50]
My ROS is indigo, so I can't catkin_make successfully. Does it have branch of indigo?

**Comment by mikaelarguedas** [comment]
It looks like it's the same branch `hydro-devel` used for all active ros distributions (including indigo).
Looking at your previous issue #49 it looks like the package that fails to build is "openslam_gmapping" (https://github.com/ros-perception/openslam_gmapping)and not this one that is called "slam_gmapping"

**Comment by vrabaud** [comment]
It does exist for Indigo but it is indeed the hydro branch: https://github.com/ros/rosdistro/blob/1c4ebb569b0d81a7319627e85628d2aa246d69d2/indigo/distribution.yaml#L13282
