### ISSUE TITLE
Release for ROS Lunar

### ISSUE THREAD

**Issue by allenh1** [ros-perception/slam_gmapping#51]
Please release this package for `lunar`!

**Comment by mikaelarguedas** [comment]
Now that openslam_gmapping has [been released](https://github.com/ros/rosdistro/pull/15710) this package should be releasable as well

**Comment by mikaelarguedas** [comment]
@vrabaud friendly ping :)

**Comment by mikaelarguedas** [comment]
@vrabaud any update on this ? Could we release the current kinetic version `1.3.8-0` (to avoid the need of cutting a new release)?

**Comment by vrabaud** [comment]
Finally done with https://github.com/ros/rosdistro/pull/16134
Life got in the way ...

**Comment by allenh1** [comment]
@vrabaud thanks!
