### ISSUE TITLE
Getting PoseStamped from gmapping

### ISSUE THREAD

**Issue by chowjf** [ros-perception/slam_gmapping#69]
Dear developers/users,
Recently I used gmapping packages to perform SLAM (mapping and also localization), but the pose information was generated via /tf2 msg. To compared with other potential packages, I visualized the pose via matlab but the resultant graph was frustrating. Anyone can help? Or how should I able to get PoseStamped data from gmapping. Below is the link for necessary files:

1) Path plotted (gmapping): https://drive.google.com/open?id=1W3Sc9aVUZFeef0X45R-t8AGAqXkQ4pP5

2) bag file contains laser scan and /tf: https://drive.google.com/file/d/19zNZB-qjVp0ekyj1X31aNkCwmRXktwor/view?usp=sharing

3) launch files: https://drive.google.com/open?id=1Dfuy7d-Id2NHfX4LaLDfhIuRkXBkUa6_

4) bag file contains /tf2 generated by gmapping: https://drive.google.com/open?id=1gXtjN8qTR_DGWuka-3byzuTXSigFgJip

5) comparison of alternative package: https://drive.google.com/open?id=15FntJ4xu5MvVrATU-9CXk7TvI9C2FkVV

**Comment by LuigiCerone** [comment]
Any news on this?

**Comment by chowjf** [comment]
You can use hector_trajectory_server node to listen to /tf message and publish as trajectory path which provides more stable outcome.
