### ISSUE TITLE
kinetic branch vanishes?

### ISSUE THREAD

**Issue by vinbo** [ros-perception/slam_gmapping#78]
I followed the link https://www.ros.org/browse/details.php?distro=kinetic&name=gmapping , which saying there is a kinetic version here, but there is not. 
What happened? and what should I do if I'm using ros kinetic?

**Comment by k-okada** [comment]
Kinetic uses `hydro-devel` branch, and you can also install by `apt-get install ros-kinetic-slam-gmapping` 

https://github.com/ros/rosdistro/blob/74145806677c295bc60e139f791808c733e1acbe/kinetic/distribution.yaml#L13914-L13926

**Comment by vinbo** [comment]
thank you
