### ISSUE TITLE
Release new version for melodic?

### ISSUE THREAD

**Issue by awesomebytes** [ros-perception/slam_gmapping#89]
gmapping on melodic on Gentoo needs this commit: https://github.com/ros-perception/slam_gmapping/commit/d1a10e7145e70ffccf30a56c372bac934fc1b04a
About removing 'signals' to be able to compile with Boost > 1.70.

Could we get a new release please? Thanks!

**Comment by mikeferguson** [comment]
Looks like @k-okada did the last release, but this package is officially maintained by "orphaned packages list" - I'll go ahead and do a release for you

**Comment by mikeferguson** [comment]
https://github.com/ros/rosdistro/pull/24095
